<h1>Relatório de NumPy</h1>
<h3>Introdução</h3>

- Biblioteca usada para **facilitar** o uso de dados numéricos em python
- É compilada baseada na linguagem C, por isso é de rápida execução
- Instalação:

In [ ]:
pip install numpy

<h3>Numpy Arrays x Python Lists</h3>

- Python Lists
    - Possui index
    - É possível utilizar mais de um tipo de dado na **mesma** lista
    - Utiliza Espaços separados na memória, sendo considerado um **map** e não um **array**
- Numpy Arrays
    - Possui index
    - Apenas um tipo de dado por lista
    - O espaço alocado na memória é **contínuo**, sendo considerado um array indexado

In [1]:
import numpy as np

In [2]:
# Criando lista em python
python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Criando array em numpy
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(python_list)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


<h3>Vetores e Matrizes</h3>

- É possível montar **vetores** e **matrizes** com um numpy array

In [3]:
# Criando Vetor
vetor = np.array([1, 2, 3, 4, 5])

# Criando Matriz
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(vetor)
print(matrix)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Criando um array "descartável", tem um começo, um fim e um passo
arranged = np.arange(0, 11, 2)
arranged

array([ 0,  2,  4,  6,  8, 10])

In [5]:
# Para saber o formato do array, se é uma matriz ou vetor
vetor.shape
matrix.shape
arranged.shape

(6,)

In [6]:
# Para criar array com apenas 0
np.zeros(3)

array([0., 0., 0.])

In [7]:
# Também é possível criar matrizes com 0
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [8]:
# Para criar array com apenas 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
# Matrizes também são possíveis
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Para criar uma matriz DIAGONAL
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [11]:
# O método linspace() é usado para criar um array com os números espaçados igualmente, sendo ditado quantas casas deseja visualizar
np.linspace(0, 11, 6)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

<h3>Numpy Random</h3>

- Biblioteca do numpy criada com o objetivo de ser randômica, retornar números aleatórios em suas estruturas de dados
- É separado em 3 **principais** categorias
    - Random Generator
    - Legacy Generator
    - Bit Generator

In [12]:
# Esse método retorna um array ou uma matriz com números aleatórios entre 0 e 1
np.random.rand(1)

array([0.96091523])

<h3>Array Slicing</h3>

- Funciona como slicing de listas python
- Start - End - Step

In [13]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[1:4:2]

array([2, 4])

In [14]:
indices = [0, 5, 8]
array[indices]

array([1, 6, 9])

<h2>Operações Básicas com NumPy</h2>

- Operações muito usadas na manipulação de dados
    - Média
    - Desvio Padrão
    - Variância
- Simplificadas pela biblioteca

In [17]:
array_teste = np.arange(0,25)
np.mean(array_teste)

np.float64(12.0)

In [18]:
np.std(array_teste)

np.float64(7.211102550927978)

In [19]:
np.var(array_teste)

np.float64(52.0)

<h3>Operações Matemáticas</h3>

In [21]:
array_teste2 = np.arange(0, 15)
np.sum(array_teste2) # Soma todos os elementos

np.int64(105)

In [22]:
np.prod(array_teste2) # Produto de todos os elementos

np.int64(0)

In [23]:
np.cumsum(array_teste2) # Soma acumulada do array inteiro

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [27]:
array_final = np.add([1, 3, 15, 4, 6, 5], [67, 4, 34, 90, 4, 1]) # Funciona apenas com arrays de mesmo SHAPE
array_final

array([68,  7, 49, 94, 10,  6])

- A multiplicação de matrizes funciona no formato X

In [29]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.eye(2)

In [31]:
np.dot(matrix1, matrix2) # Foram multiplicados por 1

array([[1., 2.],
       [3., 4.]])

<h1><b>Fim</h1>