<h1>Relatório de NumPy</h1>
<h3>Introdução</h3>

- Biblioteca usada para **facilitar** o uso de dados numéricos em python
- É compilada baseada na linguagem C, por isso é de rápida execução
- Instalação:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


<h3>Numpy Arrays x Python Lists</h3>

- Python Lists
    - Possui index
    - É possível utilizar mais de um tipo de dado na **mesma** lista
    - Utiliza Espaços separados na memória, sendo considerado um **map** e não um **array**
- Numpy Arrays
    - Possui index
    - Apenas um tipo de dado por lista
    - O espaço alocado na memória é **contínuo**, sendo considerado um array indexado

In [6]:
import numpy as np

In [11]:
# Criando lista em python
python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Criando array em numpy
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(python_list)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3>Vetores e Matrizes</h3>

- É possível montar **vetores** e **matrizes** com um numpy array

In [13]:
# Criando Vetor
vetor = np.array([1, 2, 3, 4, 5])

# Criando Matriz
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(vetor)
print(matrix)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Criando um array "descartável", tem um começo, um fim e um passo
arranged = np.arange(0, 11, 2)
arranged

array([ 0,  2,  4,  6,  8, 10])

In [16]:
# Para saber o formato do array, se é uma matriz ou vetor
vetor.shape
matrix.shape
arranged.shape

(6,)

In [18]:
# Para criar array com apenas 0
np.zeros(3)

array([0., 0., 0.])

In [19]:
# Também é possível criar matrizes com 0
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [20]:
# Para criar array com apenas 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
# Matrizes também são possíveis
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Para criar uma matriz DIAGONAL
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
# O método linspace() é usado para criar um array com os números espaçados igualmente, sendo ditado quantas casas deseja visualizar
np.linspace(0, 11, 6)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

<h3>Numpy Random</h3>

- Biblioteca do numpy criada com o objetivo de ser randômica, retornar números aleatórios em suas estruturas de dados
- É separado em 3 **principais** categorias
    - Random Generator
    - Legacy Generator
    - Bit Generator

In [26]:
# Esse método retorna um array ou uma matriz com números aleatórios entre 0 e 1
np.random.rand(1)

array([0.8386351])

0.0
